# Generated by Django 5.1 on 2024-10-09 02:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BikeArea",
            fields=[
                ("BikeArea_id", models.AutoField(primary_key=True, serialize=False)),
                ("BikeArea", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "permissions": [("edit_bikearea", "Can change bike area")],
            },
        ),
        migrations.CreateModel(
            name="BikeClass",
            fields=[
                ("BikeClass_id", models.AutoField(primary_key=True, serialize=False)),
                ("BikeClass", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FundSource",
            fields=[
                ("FundSource_id", models.AutoField(primary_key=True, serialize=False)),
                ("FundSource", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("Region_id", models.AutoField(primary_key=True, serialize=False)),
                ("Region", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RoadSection",
            fields=[
                ("RoadSection_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "RoadSection",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Typeofwork",
            fields=[
                ("Typeofwork_id", models.AutoField(primary_key=True, serialize=False)),
                ("Typeofwork", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="BikeAreaAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("old_value", models.CharField(blank=True, max_length=255, null=True)),
                ("new_value", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "BikeArea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="atdb.bikearea"
                    ),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BikeClassAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("old_value", models.CharField(blank=True, max_length=255, null=True)),
                ("new_value", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "BikeClass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="atdb.bikeclass"
                    ),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="bikelanetbl",
            fields=[
                ("Bikelane_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Bikelane_Code",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("Length", models.DecimalField(decimal_places=10, max_digits=20)),
                ("StartPointX", models.DecimalField(decimal_places=10, max_digits=20)),
                ("StartPointY", models.DecimalField(decimal_places=10, max_digits=20)),
                ("EndPointX", models.DecimalField(decimal_places=10, max_digits=20)),
                ("EndPointY", models.DecimalField(decimal_places=10, max_digits=20)),
                ("BikeDate", models.DateField(blank=True, null=True)),
                ("Remarks", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "BikeArea",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="BikeArea_name",
                        to="atdb.bikearea",
                    ),
                ),
                (
                    "BikeClass",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="BikeClass_name",
                        to="atdb.bikeclass",
                    ),
                ),
                (
                    "FundSource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="FundSource_name",
                        to="atdb.fundsource",
                    ),
                ),
                (
                    "Region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Region_name",
                        to="atdb.region",
                    ),
                ),
                (
                    "RoadSection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="RoadSection_name",
                        to="atdb.roadsection",
                    ),
                ),
                (
                    "Typeofwork",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Typeofwork_name",
                        to="atdb.typeofwork",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BikelaneAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("action", models.CharField(max_length=50)),
                ("old_data", models.TextField(blank=True, null=True)),
                ("new_data", models.TextField(blank=True, null=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bikelane",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="atdb.bikelanetbl",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FundSourceAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("old_value", models.CharField(blank=True, max_length=255, null=True)),
                ("new_value", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "FundSource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="atdb.fundsource",
                    ),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegionAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("old_value", models.CharField(blank=True, max_length=255, null=True)),
                ("new_value", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "Region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="atdb.region"
                    ),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoadSectionAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("old_value", models.CharField(blank=True, max_length=255, null=True)),
                ("new_value", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "RoadSection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="atdb.roadsection",
                    ),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TypeofworkAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("old_value", models.CharField(blank=True, max_length=255, null=True)),
                ("new_value", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "edited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "typeofwork",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="atdb.typeofwork",
                    ),
                ),
            ],
        ),
    ]
