# Generated by Django 5.1 on 2024-08-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="bikelanetbl",
            fields=[
                ("Bikelane_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Bikelane_Code",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("Typeofwork", models.CharField(blank=True, max_length=250, null=True)),
                ("Region", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "RoadSection",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("Length", models.DecimalField(decimal_places=10, max_digits=20)),
                ("StartPointX", models.DecimalField(decimal_places=10, max_digits=20)),
                ("StartPointY", models.DecimalField(decimal_places=10, max_digits=20)),
                ("EndPointX", models.DecimalField(decimal_places=10, max_digits=20)),
                ("EndPointY", models.DecimalField(decimal_places=10, max_digits=20)),
                ("BikeClass", models.CharField(blank=True, max_length=250, null=True)),
                ("BikeDate", models.DateField()),
                ("FundSource", models.CharField(blank=True, max_length=250, null=True)),
                ("Remarks", models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
