# Generated by Django 5.1 on 2024-08-09 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atdb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Typeofwork",
            fields=[
                ("Typeofwork_id", models.AutoField(primary_key=True, serialize=False)),
                ("Typeofwork", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="bikelanetbl",
            name="Typeofwork",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Typeofwork_name",
                to="atdb.typeofwork",
            ),
        ),
    ]
