# Generated by Django 5.1 on 2024-10-09 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("atdb", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bikearea",
            options={},
        ),
    ]
