# Generated by Django 5.1 on 2024-08-09 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atdb", "0002_typeofwork_alter_bikelanetbl_typeofwork"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                ("Region_id", models.AutoField(primary_key=True, serialize=False)),
                ("Region", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="bikelanetbl",
            name="Region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Region_name",
                to="atdb.region",
            ),
        ),
    ]
