# Generated by Django 5.1 on 2024-10-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atdb", "0002_alter_bikearea_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="bikelanetbl",
            name="Province",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
