# Generated by Django 5.1 on 2024-08-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atdb", "0003_region_alter_bikelanetbl_region"),
    ]

    operations = [
        migrations.CreateModel(
            name="BikeArea",
            fields=[
                ("BikeArea_id", models.AutoField(primary_key=True, serialize=False)),
                ("BikeArea", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
