# Generated by Django 5.1 on 2024-10-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atdb", "0004_alter_bikelanetbl_endpointx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bikelanetbl",
            name="status",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
