# Generated by Django 5.1 on 2024-08-09 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atdb", "0004_bikearea"),
    ]

    operations = [
        migrations.AddField(
            model_name="bikelanetbl",
            name="BikeArea",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="BikeArea_name",
                to="atdb.bikearea",
            ),
        ),
    ]
