# Generated by Django 5.1 on 2024-08-09 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atdb", "0005_bikelanetbl_bikearea"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoadSection",
            fields=[
                ("RoadSection_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "RoadSection",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="bikelanetbl",
            name="RoadSection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="RoadSection_name",
                to="atdb.roadsection",
            ),
        ),
    ]
