# Generated by Django 5.1 on 2024-08-09 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atdb", "0006_roadsection_alter_bikelanetbl_roadsection"),
    ]

    operations = [
        migrations.CreateModel(
            name="BikeClass",
            fields=[
                ("BikeClass_id", models.AutoField(primary_key=True, serialize=False)),
                ("BikeClass", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="bikelanetbl",
            name="BikeClass",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="BikeClass_name",
                to="atdb.bikeclass",
            ),
        ),
    ]
