# Generated by Django 5.1 on 2024-09-13 07:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atdb", "0014_fundsourceauditlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BikelaneAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("action", models.CharField(max_length=50)),
                ("old_data", models.TextField(blank=True, null=True)),
                ("new_data", models.TextField(blank=True, null=True)),
                (
                    "bikelane",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="atdb.bikelanetbl",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
