# Generated by Django 5.1 on 2024-09-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atdb", "0015_bikelaneauditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bikelanetbl",
            name="BikeDate",
            field=models.DateField(null=True),
        ),
    ]
