# Generated by Django 5.1 on 2024-09-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atdb", "0016_alter_bikelanetbl_bikedate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bikelanetbl",
            name="BikeDate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
